name: Make a release

on:
  workflow_dispatch:
    inputs:

      branch:
        description: 'Build branch to use'
        required: true
        default: 'nightly'

jobs:

  cli:
    uses: armbian/scripts/.github/workflows/build-with-docker.yml@master

    with:
      variant: 'targets-cli-beta.conf'
      rootfsarch: 'rock64'
      runner: 'big'
      branch: ${{ github.event.inputs.branch }}

    secrets:  
      GPG_KEY1: ${{ secrets.GPG_KEY1 }}
      GPG_PASSPHRASE1: ${{ secrets.GPG_PASSPHRASE1 }}
      GPG_KEY2: ${{ secrets.GPG_KEY2 }}
      GPG_PASSPHRASE2: ${{ secrets.GPG_PASSPHRASE2 }}
      SCRIPTS_ACCESS_TOKEN: ${{ secrets.SCRIPTS_ACCESS_TOKEN }}


  desktop:
    uses: armbian/scripts/.github/workflows/build-with-docker.yml@master

    with:
      variant: 'targets-desktop-beta.conf'
      rootfsarch: 'bananapi'
      runner: 'small'
      branch: ${{ github.event.inputs.branch }}

    secrets:  
      GPG_KEY1: ${{ secrets.GPG_KEY1 }}
      GPG_PASSPHRASE1: ${{ secrets.GPG_PASSPHRASE1 }}
      GPG_KEY2: ${{ secrets.GPG_KEY2 }}
      GPG_PASSPHRASE2: ${{ secrets.GPG_PASSPHRASE2 }}
      SCRIPTS_ACCESS_TOKEN: ${{ secrets.SCRIPTS_ACCESS_TOKEN }}

  jobsend:
    name: finish
    needs: [cli,desktop]
    runs-on: [ubuntu-latest]
    if: ${{ github.repository_owner == 'Armbian' }}
    steps:
      - run: |
          echo "End"
