name: Nightly builds

on:
  workflow_dispatch:

jobs:

  cli:
    uses: armbian/scripts/.github/workflows/build-with-docker.yml@master

    with:
 
      variant: 'targets-cli-beta.conf'
      runner: 'self-hosted, Linux, small'
    secrets:
      GPG_KEY1: ${{ secrets.GPG_KEY1 }}
      GPG_PASSPHRASE1: ${{ secrets.GPG_PASSPHRASE1 }}
      GPG_KEY2: ${{ secrets.GPG_KEY2 }}
      GPG_PASSPHRASE2: ${{ secrets.GPG_PASSPHRASE2 }}
      SCRIPTS_ACCESS_TOKEN: ${{ secrets.SCRIPTS_ACCESS_TOKEN }}

  desktop:
    uses: armbian/scripts/.github/workflows/build-with-docker.yml@master

    with:
      variant: 'targets-desktop-beta.conf'
      runner: 'self-hosted, Linux, big'      
    secrets:
      GPG_KEY1: ${{ secrets.GPG_KEY1 }}
      GPG_PASSPHRASE1: ${{ secrets.GPG_PASSPHRASE1 }}
      GPG_KEY2: ${{ secrets.GPG_KEY2 }}
      GPG_PASSPHRASE2: ${{ secrets.GPG_PASSPHRASE2 }}
      SCRIPTS_ACCESS_TOKEN: ${{ secrets.SCRIPTS_ACCESS_TOKEN }}
