name: Nightly builds

on:
  workflow_dispatch:

jobs:

  clean:

    name: "Delete previous tags"
    runs-on: [ubuntu-latest]
    steps:
      - name: Purge
        uses: dev-drprasad/delete-older-releases@v0.2.0
        with:
          repo: armbian/distribution
          delete_tags: true
          keep_latest: 0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  cli1:
    needs: clean
    uses: armbian/scripts/.github/workflows/build-with-docker.yml@development

    with:
 
      variant: 'cli:beta'
      runner: "ubuntu-latest"
      part: 1

    secrets:
      GPG_KEY1: ${{ secrets.GPG_KEY1 }}
      GPG_PASSPHRASE1: ${{ secrets.GPG_PASSPHRASE1 }}
      GPG_KEY2: ${{ secrets.GPG_KEY2 }}
      GPG_PASSPHRASE2: ${{ secrets.GPG_PASSPHRASE2 }}
      SCRIPTS_ACCESS_TOKEN: ${{ secrets.SCRIPTS_ACCESS_TOKEN }}
      
      
  cli2:  
    needs: clean
    uses: armbian/scripts/.github/workflows/build-with-docker.yml@development

    with:
 
      variant: 'cli:beta'
      runner: "ubuntu-latest"
      part: 2

    secrets:
      GPG_KEY1: ${{ secrets.GPG_KEY1 }}
      GPG_PASSPHRASE1: ${{ secrets.GPG_PASSPHRASE1 }}
      GPG_KEY2: ${{ secrets.GPG_KEY2 }}
      GPG_PASSPHRASE2: ${{ secrets.GPG_PASSPHRASE2 }}
      SCRIPTS_ACCESS_TOKEN: ${{ secrets.SCRIPTS_ACCESS_TOKEN }}

  cli3:  
    needs: clean
    uses: armbian/scripts/.github/workflows/build-with-docker.yml@development

    with:
 
      variant: 'cli:beta'
      runner: "ubuntu-latest"
      part: 3

    secrets:
      GPG_KEY1: ${{ secrets.GPG_KEY1 }}
      GPG_PASSPHRASE1: ${{ secrets.GPG_PASSPHRASE1 }}
      GPG_KEY2: ${{ secrets.GPG_KEY2 }}
      GPG_PASSPHRASE2: ${{ secrets.GPG_PASSPHRASE2 }}
      SCRIPTS_ACCESS_TOKEN: ${{ secrets.SCRIPTS_ACCESS_TOKEN }}

  desktop:
    needs: clean
    uses: armbian/scripts/.github/workflows/build-with-docker.yml@master

    with:
      variant: 'desktop:beta'
      runner: "big"
      part: 1
      
    secrets:
      GPG_KEY1: ${{ secrets.GPG_KEY1 }}
      GPG_PASSPHRASE1: ${{ secrets.GPG_PASSPHRASE1 }}
      GPG_KEY2: ${{ secrets.GPG_KEY2 }}
      GPG_PASSPHRASE2: ${{ secrets.GPG_PASSPHRASE2 }}
      SCRIPTS_ACCESS_TOKEN: ${{ secrets.SCRIPTS_ACCESS_TOKEN }}
