name: Sync
on:
  schedule:
    - cron:  '0 1 * * *'

  workflow_dispatch:

jobs:
  Adjust:
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v2

      - name: Add
        run: |
          
          echo '<h3 align=center><a href="#build-tools"><img src="https://raw.githubusercontent.com/armbian/build/master/.github/armbian-logo.png" alt="Armbian logo" width="144"></a><br>mirror sync</h3>'  > README.md
          echo -en "<p align=right>&nbsp;</p>\n" >> README.md
          echo -en "\n[![Sync mirror](https://github.com/armbian/mirror/actions/workflows/mirror-sync.yml/badge.svg)](https://github.com/armbian/mirror/actions/workflows/mirror-sync.yml) [![Rootfs sync](https://github.com/armbian/mirror/actions/workflows/rootfs-sync.yml/badge.svg)](https://github.com/armbian/mirror/actions/workflows/rootfs-sync.yml)" >> README.md
          
      - name: Add
        run: |

          git pull
          git add README.md

      - name: Commit files
        run: |
          git config --local user.email "info@armbian.com"
          git config --local user.name "Armbianworker"
          git commit --allow-empty -m "Update github actions" -a
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB }}
          branch: ${{ github.ref }}
