name: Make index
#
# Generates index
#

on:
  workflow_dispatch:
  workflow_run:
    workflows: ["Build train"]
    types:
      - completed
        
jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Make build list
        uses: armbian/actions/make-json@main

      - uses: actions/upload-artifact@v3
        with:
          path: assets.json
          name: assets
          if-no-files-found: ignore
