name: Make index
#
# Generates index
#

on:
  workflow_dispatch:
  workflow_run:
    workflows: ["Build train"]
    types:
      - completed

env:
   GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Make build list
        run: |
          gh release list | awk '{print $1}'

      - uses: actions/upload-artifact@v3
        with:
          path: assets.json
          name: assets
          if-no-files-found: ignore
